version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/app
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
  - location: scripts/deploy.sh
    timeout: 60
    runas: root