version: "3"   

services:
  nginx:
    environment:
      - EXPRESS_PORT=$PROD_SERVICE_PORT
      - API_HOST=$API_HOST
      - API_PORT=$API_PORT
  express:
    build:
      args:
        - EXPOSE_PORT=$PROD_SERVICE_PORT