version: "3"   

services:
  nginx:
    restart: "unless-stopped" 
    build:
      context: ./nginx
      dockerfile: "Dockerfile"
    ports:
        - '80:80'
    container_name: nginx

  express:
      environment:
        - MONGODB_URI
      build:
        context: ./server
        dockerfile: "Dockerfile"
      ports:
          - '8080:8080'
      container_name: express

