version: "3"   

services:
  express:
    environment:
        - MONGODB_URI
    build:
      context: ./server
      dockerfile: "Dockerfile.dev"
      args:
        - EXPOSE_PORT=8080
    ports:
      - 8080:8080
    env_file:
      - .env

