version: "3"   

services:
  express:
    build:
      args:
        - EXPOSE_PORT=$PROD_PORT

  nginx:
    volumes:
      - ./nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

  certbot:
    depends_on:
      - express
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"