version: "3"   

services:
  nginx:
    restart: "unless-stopped" 
    build:
      context: ./nginx
      dockerfile: "Dockerfile"
    ports:
      - '80:80'
    container_name: nginx
    volumes:
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      
  express:
      environment:
        - MONGODB_URI
      build:
        context: ./server
        dockerfile: "Dockerfile"
      container_name: express

