version: "3"   

services:
  express:
      environment:
        - MONGODB_URI
      build:
        context: ./server
        dockerfile: "Dockerfile"
      container_name: express

  nginx:
    restart: "unless-stopped" 
    build:
      context: ./nginx
      dockerfile: "Dockerfile"
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    volumes:
        - nginx.conf /etc/nginx/conf.d/
      # - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - SERVER_DOMAIN=$SERVER_DOMAIN

