version: '3'
services:
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: "Dockerfile"
    volumes:
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx/certbot/conf:/etc/letsencrypt 
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_DOMAIN=$SERVER_DOMAIN
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/etc:/etc/letsencrypt
      - ./nginx/certbot/var:/var/lib/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: "certonly --dry-run --webroot --webroot-path=/var/www/certbot --email ${SSL_EMAIL} --agree-tos --no-eff-email --staging -d ${SERVER_DOMAIN} -d www.${SERVER_DOMAIN}"
    env_file:
      - .env