version: "3"   

services:
  express:
    environment:
        - MONGODB_URI
    build:
      context: ./server
      dockerfile: "Dockerfile.dev"
      args:
        - EXPOSE_PORT=8080
    ports:
      - 8080:8080
    container_name: express

  nginx:
    depends_on:
      - express
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/templates/dev.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - API_PORT=$API_PORT
      - HOST=$HOST
      - PROXY_ADD_X_FORWARDED_FOR=$PROXY_ADD_X_FORWARDED_FOR
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

  
  
    
