version: "3"   

services:
  express:
      build:
        context: ./server
        dockerfile: "Dockerfile"
      container_name: express
      env_file:
      - ./server/.env

  nginx:
    image: nginx:latest
    restart: "unless-stopped" 
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    env_file:
      - .env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    