FROM node:16-alpine

ARG EXPOSE_PORT

WORKDIR /usr/src/app

COPY package*.json ./

COPY tsconfig.json ./

RUN npm ci

COPY ./ ./

RUN npm run build

EXPOSE ${EXPOSE_PORT}

CMD [ "npm", "run", "test" ]
