name: Deploy to Heroku

on:
  push:
    branches: main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.USER_NAME }}
          password: ${{ secrets.GCR_TOKEN }}
      
      - name: test eva
        run: echo "$MONGODB_URI"

      - name: Run docker-compose
        run: docker-compose up --exit-code-from express
